angular.module("app", ["ngCookies", "ui.router", "ui.bootstrap"])
    .config(routing)
    .service("trainingService", trainingService)
    .service("sessionService", sessionService)
    .service("userService", userService)
    .service("requestService", requestService)
    .filter("requestStatusFilter", requestStatusFilter)
    .component("tpMain", tpMainComponent)
    .component("trainingList", trainingListComponent)
    .component("tpPagination", tpPaginationComponent)
    .component("tpLogin", tpLoginComponent)
    .component("tpRegistration", tpRegistrationComponent)
    .component("createTraining", createTrainingComponent)
    .component("training", trainingComponent)
    .component("updateTraining", updateTrainingComponent)
    .component("deleteTraining", deleteTrainingComponent)
    .component("requestList", requestListComponent)
    .component("createRequest", createRequestComponent)
    .component("approveRequest", approveRequestComponent);